---
- name: setup new user and ssh key auth into ec2 instance
  vars:
    username: mid-user
    sudo_access: "{{ username }}        ALL=(root) NOPASSWD: /usr/sbin/dmidecode, /usr/sbin/lsof"
  tasks:
    - name: create a new user
      user:
        name: "{{ username }}"
    - name: copy public key to ~/.ssh/authorized_keys of new user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '{{ key }}') }}"
    - name: Write the sudoers entry
      lineinfile:
        dest: /etc/sudoers
        insertafter: EOF
        line: "{{ sudo_access }}"
        state: present
        create: no
      when: ansible_distribution_major_version <= "5"
    - name: Write the sudoers file
      lineinfile:
        dest: /etc/sudoers.d/{{ username }}
        line: "{{ sudo_access }}"
        state: present
        create: yes
        mode: 0440
      when: ansible_distribution_major_version > "5"
