# Install Splunk
---
- name: Read secret file
  include_vars: "defaults/secret.yml"

- name: Download Splunk archive
  get_url:
    url: "{{ splunk_archive_url }}"
    dest: /tmp/splunkforwarder.tgz

- name: Extract archive
  unarchive:
    src: /tmp/splunkforwarder.tgz
    dest: /opt
    remote_src: yes

# Configure Splunk Forwarder
- name: Run configuration commands
  shell: |
    newServerName=$(hostname)-bb-lonxt-shared
    /opt/splunkforwarder/bin/splunk start --accept-license --auto-ports --answer-yes --no-prompt --seed-passwd {{ splunk_password }}
    /opt/splunkforwarder/bin/splunk enable boot-start
    /opt/splunkforwarder/bin/splunk set servername $newServerName -auth {{ splunk_username }}:{{ splunk_password }}
    /opt/splunkforwarder/bin/splunk set default-hostname $newServerName -auth {{ splunk_username }}:{{ splunk_password }}
    /opt/splunkforwarder/bin/splunk set deploy-poll {{ splunk_server_name }}:{{ splunk_port }} -auth {{ splunk_username }}:{{ splunk_password }}
    /opt/splunkforwarder/bin/splunk restart --answer-yes
