# This playbook is responsible to remove TrendMicro from the given list of EC2 instances
# Command to run this playbook:
# ansible-playbook -i inventory/inventory -e "id=<inventory-id> loginuser=<login-user-name>" playbooks/trendmicro/remove.yml

---
- name: Install and activate Trendmicro
  hosts: "{{ id }}"
  remote_user: "{{ loginuser }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Checking if TrendMicro service exists
      shell: |
        export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin:/bin/bash
        service ds_agent status
      register: trendmicro_status
      failed_when: false

    - debug:
        msg: "TrendMicro Deep Security agent service doesn't exist."
      when: trendmicro_status.rc != 0

    - name: Remove TrendMicro service
      block:
        - name: Remove Deep Security agent (yum, dnf, zypper)
          shell: rpm -ev ds_agent
          when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "zypper"
        - name: Remove Deep Security agent (apt)
          shell: dpkg -r ds-agent
          when: ansible_pkg_mgr == "apt"
      when: trendmicro_status.rc == 0
