# This playbook is responsible to install Falcon Sensor on the given list of EC2 instances
# Command to run this playbook:
# ansible-playbook -i inventory/inventory -e "id=<inventory-id> loginuser=<login-user-name> profile=<profile-name> bucket=<bucket-name>" playbooks/falcon-sensor/run.yml

---
- name: Install and configure cmdb
  hosts: "{{ id }}"
  remote_user: "{{ loginuser }}"
  become: yes
  become_method: sudo
  roles:
    - roles/cmdb
